### PR TITLE
add multiuser support, switch to OSM

### PR DESCRIPTION
**Pull request by december-soul**
add multiuser support, switch to OSM

### CODE REVIEW

**Comment by mbernasocchi** [comment]
cool thanks, will check it next week.

**Comment by december-soul** [comment]
did you check the sources?
I have some problems that the service will stop some times. I'm new to android.
You can also take a look to my other chances.

**Comment by mbernasocchi** [comment]
Sorry havent had time yet. Will do asap

**Comment by december-soul** [comment]
done

**Pull request merged**
